## **Requisitos da professora**:

> ### **Representação e Manipulação de Dados:**
>
> - Formato de Entrega: Código-Fonte, Relatório com Capturas de Tela e Explicação Matemática
> - Objetivo: Os estudantes devem estruturar um conjunto de dados relevante para um problema prático e representá-lo usando vetores e matrizes. 
>
> ### Atividades:
> - Escolher ou coletar um conjunto de dados relevante para uma aplicação de IA.
> - Representar esses dados na forma de vetores e matrizes, utilizando Python e NumPy.
> - Implementar operações básicas de adição, multiplicação e/ou transposição de matrizes ou outra operação utilizada em sala.


In [ ]:
# Importação de Bibliotecas
# Importação do NumPy para manipulação de arrays e matrizes.
import numpy as np

In [4]:
# Criação do Dataset
# Dataset fictício para seguro automotivo.
# Cada linha representa um condutor com as seguintes características:
# [Idade do Condutor, Tempo de Habilitação (anos), Número de Sinistros]
dados = np.array([
    [25, 5, 0],
    [40, 20, 1],
    [30, 10, 0],
    [22, 2, 2],
    [35, 15, 1]
])

# Exibindo o dataset
print("Dataset (cada linha representa um condutor):")
print("Idade do Condutor, Tempo de Habilitação (anos), Número de Sinistros")
print(dados)


Dataset (cada linha representa um condutor):
Idade do Condutor, Tempo de Habilitação (anos), Número de Sinistros
[[25  5  0]
 [40 20  1]
 [30 10  0]
 [22  2  2]
 [35 15  1]]


In [5]:
# Operações Básicas de Matrizes

# 1. Adição de Matrizes
# Criação uma matriz de ajuste (com valor 2 em todos os elementos) para simular, por exemplo, 
# um acréscimo fixo nos parâmetros de avaliação.
ajuste = np.full(dados.shape, 2)
dados_ajustados = dados + ajuste

print("Dataset após adição (ajuste de +2 em cada elemento):")
print(dados_ajustados)

# 2. Multiplicação (Produto Escalar)
# Definição um vetor de pesos para cada característica, que pode representar a importância de cada fator na definição do prêmio.
pesos = np.array([10, 5, 20])  # Por exemplo: 10 para idade, 5 para tempo de habilitação e 20 para sinistros.
# Calculo do prêmio para cada condutor utilizando o produto escalar.
premios = dados.dot(pesos)

print("\nCálculo do prêmio de seguro para cada condutor (produto escalar):")
print(premios)

# 3. Transposição de Matrizes
# A transposta é útil para reorganizar os dados, por exemplo, para análise estatística por coluna.
dados_transposta = dados.T

print("\nTransposta do dataset:")
print(dados_transposta)


Dataset após adição (ajuste de +2 em cada elemento):
[[27  7  2]
 [42 22  3]
 [32 12  2]
 [24  4  4]
 [37 17  3]]

Cálculo do prêmio de seguro para cada condutor (produto escalar):
[275 520 350 270 445]

Transposta do dataset:
[[25 40 30 22 35]
 [ 5 20 10  2 15]
 [ 0  1  0  2  1]]


## Explicação Matemática

### Visão Geral
Este notebook demonstra como estruturar e manipular um conjunto de dados relevante para uma aplicação prática na área de seguros. A solução explora conceitos fundamentais de álgebra linear usando o NumPy.

### 1. Adição de Matrizes
A adição é realizada elemento a elemento. Se temos duas matrizes A e B, ambas com dimensões iguais, o elemento (i,j) da matriz resultante é:
  
> (A + B)<sub>ij</sub> = A<sub>ij</sub> + B<sub>ij</sub>

No exemplo, adicionamos um valor fixo (2) a cada elemento do dataset, simulando um ajuste.

### 2. Multiplicação (Produto Escalar)
Ao multiplicar uma matriz por um vetor, o produto resultante é obtido realizando o produto escalar de cada linha da matriz com o vetor. Formalmente, se A é uma matriz de dimensão m×n e v é um vetor de dimensão n, então o elemento i do produto é:
  
> (A · v)<sub>i</sub> = Σ<sub>j=1</sub><sup>n</sup> A<sub>ij</sub> * v<sub>j</sub>

No exemplo, o vetor `pesos` representa a importância de cada característica na definição do prêmio de seguro. O produto escalar de cada linha de `dados` com `pesos` fornece o valor do prêmio para cada condutor.

### 3. Transposição de Matrizes
A transposição de uma matriz consiste em trocar suas linhas por colunas. Se A é uma matriz, sua transposta, A<sup>T</sup>, tem elementos:
  
> (A<sup>T</sup>)<sub>ij</sub> = A<sub>ji</sub>

Isso é útil para reestruturar os dados de modo a facilitar análises que focam em cada variável separadamente.

In [6]:
# Definição de Matrizes Simples
# Duas matrizes 2x2: A e B.
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)


Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]


In [7]:
# Adição de Matrizes
# A adição é feita elemento a elemento:
# (A + B)[i][j] = A[i][j] + B[i][j]
C = A + B

print("Resultado da adição (A + B):")
print(C)


Resultado da adição (A + B):
[[ 6  8]
 [10 12]]


In [10]:
# Multiplicação de Matrizes
# Produto matricial (dot product) entre A e B.
# Ou seja, cada elemento (i, j) do resultado é:
# (A * B)[i][j] = Σ (A[i][k] * B[k][j]) para k=0 até o número de colunas de A.

D2 = np.dot(A, B)

print("Resultado da multiplicação (A x B):")
print(D)
print("\nResultado da multiplicação com np.dot:")
print(D2)


Resultado da multiplicação (A x B):
[[19 22]
 [43 50]]

Resultado da multiplicação com np.dot:
[[19 22]
 [43 50]]


In [11]:
# Transposição de Matrizes
# A transposta de uma matriz é obtida trocando suas linhas por colunas.
A_transposta = A.T
B_transposta = B.T

print("Transposta de A:")
print(A_transposta)
print("\nTransposta de B:")
print(B_transposta)


Transposta de A:
[[1 3]
 [2 4]]

Transposta de B:
[[5 7]
 [6 8]]


Referencias:


- [Documentação numpy - Arrays](https://numpy.org/doc/2.2/user/basics.creation.html)

- [Documentaçao numpy - Algebra linear](https://numpy.org/doc/2.2/reference/routines.linalg.html)

- [Matrizes - Brasil Escola](https://brasilescola.uol.com.br/matematica/matriz.htm)